# Localization file (english).
YEARS = "Term of capital placement (years): "
ERROR_1 = "Error. Enter the year again:"
INITIAL_CAPITAL = "Initial capital ($): "
ERROR_2 = "Error. Enter the initial capital again ($):"
PERCENT = "Interest rate (%/month): "
ERROR_3 = "Error. Enter the interest rate again"
INVESTMENT_INFUSION = "Investment injections ($/month): "
ERROR_4 = "Error. Enter the investment infusion again: "
PRINT_YEAR = "year"
MONTH = "month"
PRINT_INITIAL_CAPITAL = "initial"
PRINT_INITIAL_CAPITAL_1 = "capital"
PRINT_INCOME = "income"
PRINT_INVESTMENT_INFUSION = "investment"
PRINT_INVESTMENT_INFUSION_1 = "infusion"
