# Localization file (germany).
YEARS = "Laufzeit der Kapitalplatzierung (Jahre): "
ERROR_1 = "Der Fehler. Geben Sie das Jahr erneut ein: "
INITIAL_CAPITAL = "Anfangskapital ($)："
ERROR_2 = "Der Fehler. Geben Sie das Anfangskapital ($) erneut ein: "
PERCENT = "Zinssatz (% / Monat): "
ERROR_3 = "Der Fehler. Geben Sie den Zinssatz (% / Monat) erneut ein："
INVESTMENT_INFUSION = "Der Fehler. Geben Sie den Zinssatz (% / Monat) erneut ein："
ERROR_4 = "Investitionsspritzen ($ / Monat)："
PRINT_YEAR = "Jahr"
MONTH = "Monat"
PRINT_INITIAL_CAPITAL = "Hauptstadt"
PRINT_INCOME = "Menge %"
PRINT_INVESTMENT_INFUSION = "Investition"
PRINT_INVESTMENT_INFUSION_1 = "Infusion"
